### PR TITLE
LRDOCS-3662 form navigator contexts tutorial

### PR DESCRIPTION
**Pull request by mwilliams2014**
@4lejandrito let me know if anything needs updated, or if any other configuration information is needed for the BND or build.gradle files for this to work.

thx!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Hi @mwilliams2014,

I think this piece of documentation is very accurate and well put together.

Regarding your question:

To be able to implement the FormNavigatorContextProvider interface you must add a dependency to your module: `provided group: "com.liferay", name: "com.liferay.frontend.taglib.form.navigator", version: "1.0.0"`.

That should be enough.

**Comment by mwilliams2014** [comment]
Thanks! I'll add a step for the dependency.

**Comment by mwilliams2014** [comment]
@4lejandrito are you sure that is the right version of the module? Looking here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-taglib/frontend-taglib-form-navigator/bnd.bnd , it looks like the latest is 1.0.2 .

**Comment by 4lejandrito** [comment]
Hi @mwilliams2014,

I have double checked in https://repository.liferay.com and 1.0.2 is indeed the latest published version therefore you can use it.

Nice one, thanks!

**Pull request closed without merging**
